FROM ubuntu:trusty

MAINTAINER Antti Rintala <antti@rintala.it>

# It's important to note that each RUN statement will generate a new image,
# with the parent of that image being the image generated by the Dockerfile
# statement above it. For this reason we collapse the RUN statements into one
# multiline statement.

RUN apt-get -y update && \
    add-apt-repository -y ppa:nginx/stable && \
    apt-get -y update && \
    apt-get install -y nginx

ADD configuration/nginx.conf /etc/nginx/

EXPOSE 80 443

CMD ["/usr/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]
